package edu.uniajc.banco.app.entity;
// Generated 8/04/2019 05:09:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Cajero generated by hbm2java
 */
public class Cajero implements java.io.Serializable {

	private int idCajero;
	private String ubicacion;
	private String montocajero;
	private Date fecha;
	private String hora;
	private String estado;
	private Transacccion transacccion;

	public Cajero() {
	}

	public Cajero(int idCajero) {
		this.idCajero = idCajero;
	}

	public Cajero(int idCajero, String ubicacion, String montocajero, Date fecha, String hora, String estado,
			Transacccion transacccion) {
		this.idCajero = idCajero;
		this.ubicacion = ubicacion;
		this.montocajero = montocajero;
		this.fecha = fecha;
		this.hora = hora;
		this.estado = estado;
		this.transacccion = transacccion;
	}

	public int getIdCajero() {
		return this.idCajero;
	}

	public void setIdCajero(int idCajero) {
		this.idCajero = idCajero;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getMontocajero() {
		return this.montocajero;
	}

	public void setMontocajero(String montocajero) {
		this.montocajero = montocajero;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Transacccion getTransacccion() {
		return this.transacccion;
	}

	public void setTransacccion(Transacccion transacccion) {
		this.transacccion = transacccion;
	}

}
