package edu.uniajc.banco.app.entity;
// Generated 8/04/2019 05:09:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private int idCuenta;
	private Banco banco;
	private Tarjeta tarjeta;
	private TipoCuenta tipoCuenta;
	private TipoProducto tipoProducto;
	private Usuario usuario;
	private Date fechaInicio;
	private Date fechaFin;
	private Long monto;
	private String passwordWeb;
	private Integer estado;
	private Integer bloqueo;
	private Set logTrasaccions = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(int idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Cuenta(int idCuenta, Banco banco, Tarjeta tarjeta, TipoCuenta tipoCuenta, TipoProducto tipoProducto,
			Usuario usuario, Date fechaInicio, Date fechaFin, Long monto, String passwordWeb, Integer estado,
			Integer bloqueo, Set logTrasaccions) {
		this.idCuenta = idCuenta;
		this.banco = banco;
		this.tarjeta = tarjeta;
		this.tipoCuenta = tipoCuenta;
		this.tipoProducto = tipoProducto;
		this.usuario = usuario;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.monto = monto;
		this.passwordWeb = passwordWeb;
		this.estado = estado;
		this.bloqueo = bloqueo;
		this.logTrasaccions = logTrasaccions;
	}

	public int getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(int idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public TipoCuenta getTipoCuenta() {
		return this.tipoCuenta;
	}

	public void setTipoCuenta(TipoCuenta tipoCuenta) {
		this.tipoCuenta = tipoCuenta;
	}

	public TipoProducto getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(TipoProducto tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Long getMonto() {
		return this.monto;
	}

	public void setMonto(Long monto) {
		this.monto = monto;
	}

	public String getPasswordWeb() {
		return this.passwordWeb;
	}

	public void setPasswordWeb(String passwordWeb) {
		this.passwordWeb = passwordWeb;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public Integer getBloqueo() {
		return this.bloqueo;
	}

	public void setBloqueo(Integer bloqueo) {
		this.bloqueo = bloqueo;
	}

	public Set getLogTrasaccions() {
		return this.logTrasaccions;
	}

	public void setLogTrasaccions(Set logTrasaccions) {
		this.logTrasaccions = logTrasaccions;
	}

}
