package edu.uniajc.banco.app.entity;
// Generated 8/04/2019 05:09:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoProducto generated by hbm2java
 */
public class TipoProducto implements java.io.Serializable {

	private int idTipoProducto;
	private String nombre;
	private Set cuentas = new HashSet(0);

	public TipoProducto() {
	}

	public TipoProducto(int idTipoProducto) {
		this.idTipoProducto = idTipoProducto;
	}

	public TipoProducto(int idTipoProducto, String nombre, Set cuentas) {
		this.idTipoProducto = idTipoProducto;
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	public int getIdTipoProducto() {
		return this.idTipoProducto;
	}

	public void setIdTipoProducto(int idTipoProducto) {
		this.idTipoProducto = idTipoProducto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
