package edu.uniajc.banco.app.entity;
// Generated 8/04/2019 05:09:58 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * TipoCuenta generated by hbm2java
 */
@Entity()
@Table (name="tipo_cuenta")
public class TipoCuenta implements java.io.Serializable {

	@Id
    @GeneratedValue
    @Column(name="idTIPO_CUENTA")
	private int idTipoCuenta;
	
	@NotNull
	@NotEmpty
	@Column(name="Nombre")
	private String nombre;
	
	@OneToMany(mappedBy = "tipoCuenta", cascade = CascadeType.ALL)
	private Set cuentas = new HashSet(0);

	public TipoCuenta() {
	}

	public TipoCuenta(int idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	public TipoCuenta(int idTipoCuenta, String nombre, Set cuentas) {
		this.idTipoCuenta = idTipoCuenta;
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	public int getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(int idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
