package edu.uniajc.banco.app.entity;
// Generated 8/04/2019 05:09:58 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Transacccion generated by hbm2java
 */
public class Transacccion implements java.io.Serializable {

	private int idTransacccion;
	private Cajero cajero;
	private String fecha;
	private String hora;
	private Integer idCajero;
	private String debe;
	private String haber;
	private String estado;

	public Transacccion() {
	}

	public Transacccion(Cajero cajero) {
		this.cajero = cajero;
	}

	public Transacccion(Cajero cajero, String fecha, String hora, Integer idCajero, String debe, String haber,
			String estado) {
		this.cajero = cajero;
		this.fecha = fecha;
		this.hora = hora;
		this.idCajero = idCajero;
		this.debe = debe;
		this.haber = haber;
		this.estado = estado;
	}

	public int getIdTransacccion() {
		return this.idTransacccion;
	}

	public void setIdTransacccion(int idTransacccion) {
		this.idTransacccion = idTransacccion;
	}

	public Cajero getCajero() {
		return this.cajero;
	}

	public void setCajero(Cajero cajero) {
		this.cajero = cajero;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public Integer getIdCajero() {
		return this.idCajero;
	}

	public void setIdCajero(Integer idCajero) {
		this.idCajero = idCajero;
	}

	public String getDebe() {
		return this.debe;
	}

	public void setDebe(String debe) {
		this.debe = debe;
	}

	public String getHaber() {
		return this.haber;
	}

	public void setHaber(String haber) {
		this.haber = haber;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
